cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

install: gradle wrapper --gradle-version 4.5

language: java

jdk:
  - oraclejdk8

script:
  - ./gradlew build

after_success:
  - ./gradlew bintrayUpload
